---
- name: reload prometheus
  shell: /usr/local/bin/docker-compose restart prometheus
  args:
    chdir: /opt/blindstrader

- name: reload grafana
  shell: /usr/local/bin/docker-compose restart grafana
  args:
    chdir: /opt/blindstrader

- name: reload loki
  shell: /usr/local/bin/docker-compose restart loki
  args:
    chdir: /opt/blindstrader

- name: reload promtail
  shell: /usr/local/bin/docker-compose restart promtail
  args:
    chdir: /opt/blindstrader
